# Generated by Django 5.1.7 on 2025-03-21 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedeeTurul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garchig', models.CharField(max_length=500)),
                ('tailbar', models.TextField()),
                ('niitlegch', models.CharField(max_length=255)),
                ('niitelsen_ognoo', models.DateTimeField(auto_now_add=True)),
                ('eh_surwalj', models.CharField(blank=True, max_length=255, null=True)),
                ('zurag', models.ImageField(blank=True, null=True, upload_to='medee_zurag/')),
                ('uzelt', models.PositiveIntegerField(default=0)),
                ('turul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medeenuud', to='medeeapp.medeeturul')),
            ],
        ),
    ]
